### ISSUE TITLE
Support LDAP group referencing users

### ISSUE THREAD

**Issue by hrenard** [BeryJu/authentik#525]
**Is your feature request related to a problem? Please describe.**
My current OpenLDAP setup use the groupOfNames class as a group which contains a member attributes with a list of dn referencing users. 
In that case, user don't have an attribute referencing groups.

**Describe the solution you'd like**
It would be nice to have an option to switch between user reference to group reference. The membership field will reference either a user attribute or a group attribute.

**Describe alternatives you've considered**
Changing my LDAP setup or removing it.

**Additional context**
This probably add some complexity in the sync process.

**Comment by BeryJu** [comment]
Hi,

could you post an LDIF of an example group and user that I can test this with?

**Comment by hrenard** [comment]
```
 LDIF Export for cn=admin,ou=groups,dc=lyriste,dc=fr
# Server: openldap (openldap)
# Search Scope: base
# Search Filter: (objectClass=*)
# Total Entries: 1
#
# Generated by phpLDAPadmin (http://phpldapadmin.sourceforge.net) on February 4, 2021 9:23 am
# Version: 1.2.5

version: 1

# Entry 1: cn=admin,ou=groups,dc=lyriste,dc=fr
dn: cn=admin,ou=groups,dc=lyriste,dc=fr
cn: admin
member: uid=hrenard,ou=users,dc=lyriste,dc=fr
member: uid=mvaubourg,ou=users,dc=lyriste,dc=fr
member: uid=lvandevelde,ou=users,dc=lyriste,dc=fr
objectclass: groupOfNames
objectclass: top
```

**Comment by BeryJu** [comment]
Also, just to clarify, the groups themselves are synced successfully?

**Comment by hrenard** [comment]
I can't really say because  #527 but the number of groups seems good.

**Comment by BeryJu** [comment]
So it turns out Active Directory also stores users of a group in the `member` attribute, I'll rewrite the LDAP Sync to use a Field on the group objects rather than on the user object.

**Comment by BeryJu** [comment]
@hrenard could you try the build in #528? this includes all the previous LDAP fixes and should fully fix LDAP sync for your setup
