### ISSUE TITLE
Show code for TOTP setup

### ISSUE THREAD

**Issue by tigattack** [BeryJu/authentik#591]
**Is your feature request related to a problem? Please describe.**
I'm unable to scan a QR code with my desktop TOTP app, but I can enter a code.

**Describe the solution you'd like**
After clicking "Enable Time-Based OTP", I would like the raw code to be shown as well as QR code.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by BeryJu** [comment]
In the current version you can do this by hand by using the `data-otpuri` attribute of the QR Code.

In the next version I will add a button to copy the URL on the TOTP Enrollment stage.
