### ISSUE TITLE
Postgres Password Incorrect when deploying via Helm

### ISSUE THREAD

**Issue by M1kep** [BeryJu/authentik#745]
**Describe the bug**
When deploying Authentic via Helm onto a Kubernetes cluster the authentic-web deployment fails to provision as it cannot connect to the Postgresql server. When reviewing the logs, it appears it's attempting to use an incorrect password.

**To Reproduce**
1. Deploy Authentik to Kubernetes via Cluster with no values.yaml

**Expected behavior**
Authentik to deploy.

**Screenshots**

**Logs**
```
2021-04-16 20:51:40.437 GMT [1347] FATAL:  password authentication failed for user "postgres"
2021-04-16 20:51:40.437 GMT [1347] DETAIL:  Password does not match for user "postgres".
	Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
```

**Version and Deployment (please complete the following information):**
Helm Chart Version: authentik:2021.4.1
**Additional context**

**Comment by BeryJu** [comment]
Hey, what does your values.yaml file look like?

I think this error might occur if no values file is specified, in which case I'll add a note for that (since you *should* keep your passowrds in a file and not just k8s)

**Comment by M1kep** [comment]
I am not currently using any values.yaml, so that is most likely the issue. I do think it'd be very helpful to have a section outlining the bare minimum set of values that should be provided for the values in this Helm chart.
