### ISSUE TITLE
Ability to disable sentry ?

### ISSUE THREAD

**Issue by nicolasvac** [BeryJu/authentik#747]
**Is your feature request related to a problem? Please describe.**
Just as the title says, can we get analytics as an opt-in feature instead of being enabled by default ?

This is common for big open-source projects or for the becoming ones.

**Comment by BeryJu** [comment]
Sentry is only activated when `AUTHENTIK_ERROR_REPORTING__ENABLED` (for docker-compose) or `config.errorReporting.enabled` (for Kubernetes) is set (this enables it for both the frontend and backend)

**Comment by nicolasvac** [comment]
Hi, i'm very sorry. 

I actually just copy-pasted the default config to try it out and i did not notice there was a .env option.

Just a tip, maybe put it in a separate box on the documentation ?

**Comment by BeryJu** [comment]
It's kinda phrased like that to encourage people to enable it, as it does greatly help the development.

**Comment by nicolasvac** [comment]
Ok then, thank you for the clarifications. 

Have a great weekend.
