### ISSUE TITLE
Nextcloud integration ssl documentation request

### ISSUE THREAD

**Issue by gianlazz** [BeryJu/authentik#750]
**Describe the bug**
This is not really a but but more of a documentation detail request.

When following along with the nextcloud integration I ran into an issue where authentik reported an error because a request was made from http -> https. The documentation makes note about requiring ssl to be configured in the nextcloud deployment. While this ended up being a hint that pointed me in the right direction it was challenging to find the solution.

In the official apache based nextcloud docker image from docker hub it has a section about using it behind a reverse proxy. The key to overcome the issue mentioned from http -> https was making use of the `OVERWRITEPROTOCOL` environment variable on the `nextcloud:stable-apache` image and setting it to `https`. From there I was able to successfully integrate nextcloud.

**Version and Deployment (please complete the following information):**
 - authentik version: beryju/authentik:2021.4.2
 - Deployment: helm

**Additional context**
Is there a place where pull requests can be made for the project documentation? On initial glance the source for the docs didn't appear to be in this repo.

**Comment by BeryJu** [comment]
Hey, the docs indeed in this repo, for example: https://github.com/BeryJu/authentik/blob/master/website/docs/integrations/services/nextcloud/index.md

The reason why I hadn't added any too specific instructions is because I don't know how the user is running nextcloud.

**Comment by gianlazz** [comment]
That's fair, however one other comment I have is that the https://github.com/BeryJu/authentik/blob/master/website/docs/integrations/services/nextcloud/index.md documentation assumes that the `SSO & SAML Authentication` app bundle is already downloaded and enabled. At least on my fresh install of nextcloud I looked for an already existing `SSO & SAML Authentication` section as per the documentation and found it confusing that it wasn't already there.

**Comment by BeryJu** [comment]
Cheers, I've added notes for both of your comments @gianlazz
