### ISSUE TITLE
Can't change password, deny page is presented.

### ISSUE THREAD

**Issue by Akruidenberg** [BeryJu/authentik#763]
**Describe the bug**

When changing the password, the error "Pending user has no backend is shown".

**To Reproduce**
1. Go to users tab
2. Click on '..Reset Password..'
3. Go to the URL and change password

**Expected behavior**
No deny page must be presented.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/18529293/115441057-b84a8500-a210-11eb-8817-494735091f64.png)

**Logs**

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.4.3
 - Deployment: Docker Compose

**Additional context**
Maybe additional documentation is required.

**Comment by BeryJu** [comment]
Hey,

thanks for reporting this issue! How did you create the recovery flow? Did you import the example from https://goauthentik.io/docs/flow/examples#recovery-with-email-verification ?

**Comment by Akruidenberg** [comment]
> Hey,
> 
> thanks for reporting this issue! How did you create the recovery flow? Did you import the example from https://goauthentik.io/docs/flow/examples#recovery-with-email-verification ?

Yes! Thats right.
